version: '3.1'

services:

  mongo:
    build:
      context: ./Containers/mongodb/
      dockerfile: Dockerfile
    ports:
      - 27017:27017

    volumes:
      - "./mongoDump:/data/backup"
      - "./current_data:/data/db"  
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: snoozy
      MONGO_INITDB_ROOT_PASSWORD: deadoralive

  python: 
      build:
        context: ./
        dockerfile: Dockerfile
      depends_on:
      - "mongo"